# ข้อที่ 1 Filter ราคาปิดที่มีค่ามากกว่า 60,000

In [1]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.87-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.21.6)
Collecting requests>=2.26
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 689 kB/s
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.24.0->yfinance) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)
Installing collected packages: requests, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
Successfully installed requests-2.28.1 yfinance-0.1.87

In [4]:
import pandas as pd
import yfinance as yf

In [11]:
t0 = '2021-01-01'
t1 = '2022-11-30'

In [12]:
data = yf.download('BTC-USD', start=t0, end=t1)

[*********************100%***********************]  1 of 1 completed

In [13]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-01-01,28994.009766,29600.626953,28803.585938,29374.152344,29374.152344,40730301359
2021-01-02,29376.455078,33155.117188,29091.181641,32127.267578,32127.267578,67865420765
2021-01-03,32129.408203,34608.558594,32052.316406,32782.023438,32782.023438,78665235202
2021-01-04,32810.949219,33440.218750,28722.755859,31971.914062,31971.914062,81163475344
2021-01-05,31977.041016,34437.589844,30221.187500,33992.429688,33992.429688,67547324782
...,...,...,...,...,...,...
2022-11-25,16602.269531,16603.316406,16388.404297,16521.841797,16521.841797,18678255976
2022-11-26,16521.576172,16666.863281,16416.228516,16464.281250,16464.281250,18000008764
2022-11-27,16463.882812,16594.406250,16437.025391,16444.626953,16444.626953,20443898509
2022-11-28,16440.222656,16482.933594,16054.530273,16217.322266,16217.322266,27743025156
2022-11-29,16217.639648,16522.257812,16139.396484,16444.982422,16444.982422,23581685468

In [14]:
df = data.copy()

In [15]:
df['Return'] = df['Close'].pct_change()

In [16]:
df

,Open,High,Low,Close,Adj Close,Volume,Return
Date,,,,,,,
2021-01-01,28994.009766,29600.626953,28803.585938,29374.152344,29374.152344,40730301359,NaN
2021-01-02,29376.455078,33155.117188,29091.181641,32127.267578,32127.267578,67865420765,0.093726
2021-01-03,32129.408203,34608.558594,32052.316406,32782.023438,32782.023438,78665235202,0.020380
2021-01-04,32810.949219,33440.218750,28722.755859,31971.914062,31971.914062,81163475344,-0.024712
2021-01-05,31977.041016,34437.589844,30221.187500,33992.429688,33992.429688,67547324782,0.063197
...,...,...,...,...,...,...,...
2022-11-25,16602.269531,16603.316406,16388.404297,16521.841797,16521.841797,18678255976,-0.004976
2022-11-26,16521.576172,16666.863281,16416.228516,16464.281250,16464.281250,18000008764,-0.003484
2022-11-27,16463.882812,16594.406250,16437.025391,16444.626953,16444.626953,20443898509,-0.001194
2022-11-28,16440.222656,16482.933594,16054.530273,16217.322266,16217.322266,27743025156,-0.013822
2022-11-29,16217.639648,16522.257812,16139.396484,16444.982422,16444.982422,23581685468,0.014038

In [17]:
df[df.Close > 60000]

,Open,High,Low,Close,Adj Close,Volume,Return
Date,,,,,,,
2021-03-13,57343.371094,61683.863281,56217.972656,61243.085938,61243.085938,60669829814,0.068217
2021-04-11,59846.230469,60790.554688,59289.796875,60204.964844,60204.964844,46280252580,0.006886
2021-04-13,59890.019531,63742.285156,59869.957031,63503.457031,63503.457031,69983454362,0.060274
2021-04-14,63523.753906,64863.097656,61554.796875,63109.695312,63109.695312,77451779687,-0.006201
2021-04-15,63075.195312,63821.671875,62208.964844,63314.011719,63314.011719,60954381579,0.003237
2021-04-16,63258.503906,63594.722656,60222.531250,61572.789062,61572.789062,84293007468,-0.027501
2021-04-17,61529.921875,62572.175781,60361.351562,60683.820312,60683.820312,66138759198,-0.014438
2021-10-15,57345.902344,62757.128906,56868.144531,61593.949219,61593.949219,51780081801,0.074534
2021-10-16,61609.527344,62274.476562,60206.121094,60892.179688,60892.179688,34250964237,-0.011393
2021-10-17,60887.652344,61645.523438,59164.468750,61553.617188,61553.617188,29032367511,0.010862
2021-10-18,61548.804688,62614.660156,60012.757812,62026.078125,62026.078125,38055562075,0.007676
2021-10-19,62043.164062,64434.535156,61622.933594,64261.992188,64261.992188,40471196346,0.036048
2021-10-20,64284.585938,66930.390625,63610.675781,65992.835938,65992.835938,40788955582,0.026934
2021-10-21,66002.234375,66600.546875,62117.410156,62210.171875,62210.171875,45908121370,-0.057319
2021-10-22,62237.890625,63715.023438,60122.796875,60692.265625,60692.265625,38434082775,-0.024400
2021-10-23,60694.628906,61743.878906,59826.523438,61393.617188,61393.617188,26882546034,0.011556
2021-10-24,61368.343750,61505.804688,59643.343750,60930.835938,60930.835938,27316183882,-0.007538
2021-10-25,60893.925781,63729.324219,60691.800781,63039.824219,63039.824219,31064911614,0.034613
2021-10-26,63032.761719,63229.027344,59991.160156,60363.792969,60363.792969,34878965587,-0.042450
2021-10-28,58470.730469,62128.632812,58206.917969,60622.136719,60622.136719,45257083247,0.036588
2021-10-29,60624.871094,62927.609375,60329.964844,62227.964844,62227.964844,36856881767,0.026489
2021-10-30,62239.363281,62330.144531,60918.386719,61888.832031,61888.832031,32157938616,-0.005450
2021-10-31,61850.488281,62406.171875,60074.328125,61318.957031,61318.957031,32241199927,-0.009208
2021-11-01,61320.449219,62419.003906,59695.183594,61004.406250,61004.406250,36150572843,-0.005130
2021-11-02,60963.253906,64242.792969,60673.054688,63226.402344,63226.402344,37746665647,0.036424
2021-11-03,63254.335938,63516.937500,61184.238281,62970.046875,62970.046875,36124731509,-0.004055
2021-11-04,62941.804688,63123.289062,60799.664062,61452.230469,61452.230469,32615846901,-0.024104
2021-11-05,61460.078125,62541.468750,60844.609375,61125.675781,61125.675781,30605102446,-0.005314
2021-11-06,61068.875000,61590.683594,60163.781250,61527.480469,61527.480469,29094934221,0.006573
2021-11-07,61554.921875,63326.988281,61432.488281,63326.988281,63326.988281,24726754302,0.029247
2021-11-08,63344.066406,67673.742188,63344.066406,67566.828125,67566.828125,41125608330,0.066952
2021-11-09,67549.734375,68530.335938,66382.062500,66971.828125,66971.828125,42357991721,-0.008806
2021-11-10,66953.335938,68789.625000,63208.113281,64995.230469,64995.230469,48730828378,-0.029514
2021-11-11,64978.890625,65579.015625,64180.488281,64949.960938,64949.960938,35880633236,-0.000697
2021-11-12,64863.980469,65460.816406,62333.914062,64155.941406,64155.941406,36084893887,-0.012225
2021-11-13,64158.121094,64915.675781,63303.734375,64469.527344,64469.527344,30474228777,0.004888
2021-11-14,64455.371094,65495.179688,63647.808594,65466.839844,65466.839844,25122092191,0.015470
2021-11-15,65521.289062,66281.570312,63548.144531,63557.871094,63557.871094,30558763548,-0.029159
2021-11-16,63721.195312,63721.195312,59016.335938,60161.246094,60161.246094,46844335592,-0.053441
2021-11-17,60139.621094,60823.609375,58515.410156,60368.011719,60368.011719,39178392930,0.003437

# ข้อที่ 2 Filter Return ที่มีค่ามากกว่า 0

In [18]:
df[df['Return'] > 0]

,Open,High,Low,Close,Adj Close,Volume,Return
Date,,,,,,,
2021-01-02,29376.455078,33155.117188,29091.181641,32127.267578,32127.267578,67865420765,0.093726
2021-01-03,32129.408203,34608.558594,32052.316406,32782.023438,32782.023438,78665235202,0.020380
2021-01-05,31977.041016,34437.589844,30221.187500,33992.429688,33992.429688,67547324782,0.063197
2021-01-06,34013.613281,36879.699219,33514.035156,36824.363281,36824.363281,75289433811,0.083311
2021-01-07,36833.875000,40180.367188,36491.191406,39371.042969,39371.042969,84762141031,0.069157
...,...,...,...,...,...,...,...
2022-11-18,16687.912109,16947.058594,16564.611328,16697.777344,16697.777344,26862218609,0.000615
2022-11-19,16696.220703,16797.876953,16570.410156,16711.546875,16711.546875,16106223492,0.000825
2022-11-22,15782.300781,16253.047852,15656.606445,16189.769531,16189.769531,30726828760,0.025494
2022-11-23,16195.588867,16638.193359,16170.502930,16610.707031,16610.707031,32958875628,0.026000
2022-11-29,16217.639648,16522.257812,16139.396484,16444.982422,16444.982422,23581685468,0.014038

# ข้อที่ 3 สร้าง Function แล้วให้ Print โดยมี Condition ที่ว่าหาก Return > 0 ให้ Print "Gain" หาก Return < 0 ให้ปริ้น "Loss"

In [21]:
def ret_con(df):
  if (df > 0):
    print('Gain')

  elif (df < 0):
    print('Loss')

In [22]:
for i in range(len(df.Close)):
  ret_con(df.iloc[i,-1])

Gain
Gain
Loss
Gain
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Gain
Loss
Loss
Loss
Gain
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Gain
Loss
Loss
Gain
Loss
Loss
Loss
Loss
Gain
Loss
Gain
Loss
Gain
Loss
Gain
Gain
Gain
Gain
Gain
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Gain
Loss
Loss
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Gain
Gain
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Gain
Loss
Gain
Loss
Loss
Loss
Loss
Gain
Loss
Loss
Loss
Loss
Loss
Gain
Gain
Loss
Loss
Gain
Gain
Loss
Gain
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Loss
Loss
Loss
Gain
Loss
Gain
Loss
Gain
Loss
Gain
Loss
Loss
Loss
Gain
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Loss
Gain
Loss
Gain
Loss
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Loss
Loss
Gain
Gain
Gain
Loss
Gain
Loss
Loss
Gain
Loss
Gain
Loss
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Gain
Gain
Gain
Gain
Gain
Gain
Gain
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Gain
Gain
Gain
Loss
Gain
Loss
Gain
Loss
Gain
Loss
Loss
Loss
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Loss
Gain
Loss
Loss
Loss
Gain
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Loss
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Loss
Gain
Loss
Gain
Loss
Gain
Gain
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Gain
Loss
Loss
Loss
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Loss
Gain
Gain
Gain
Loss
Gain
Loss
Loss
Loss
Gain
Gain
Gain
Loss
Loss
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Loss
Loss
Loss
Gain
Loss
Gain
Loss
Loss
Loss
Loss
Loss
Loss
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Loss
Loss
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Gain
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Gain
Gain
Gain
Gain
Gain
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Gain
Loss
Gain
Loss
Loss
Loss
Loss
Loss
Gain
Loss
Gain
Gain
Gain
Gain
Loss
Gain
Loss
Gain
Loss
Gain
Gain
Loss
Gain
Loss
Loss
Loss
Gain
Gain
Gain
Gain
Loss
Gain
Loss
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Loss
Loss
Loss
Loss
Gain
Loss
Gain
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Loss
Loss
Loss
Gain
Gain
Loss
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Loss
Loss
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Loss
Loss
Gain
Gain
Loss
Gain
Loss
Gain
Loss
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Gain
Loss
Loss
Gain
Gain
Gain
Gain
Gain
Gain
Loss
Loss
Loss
Gain
Gain
Loss
Gain
Loss
Loss
Gain
Loss
Loss
Loss
Gain
Loss
Gain
Gain
Loss
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Gain
Gain
Gain
Loss
Gain
Gain
Loss
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Gain
Gain
Loss
Loss
Loss
Loss
Gain
Loss
Loss
Loss
Gain
Gain
Loss
Gain
Gain
Gain
Loss
Loss
Gain
Gain
Loss
Loss
Loss
Loss
Loss
Gain

# แถม

In [27]:
sum1 = len(df.loc[(df['Return'] < 0)])
sum2 = len(df.loc[(df['Return'] > 0)])

sum = len(df.Return)

per1 = (sum1/sum *100)
per2 = (sum2/sum *100)

print("Number of expected loss are {0} times in {1} about {2:.2f}%".format(sum1,sum, per1))
print("Number of expected gain are {0} times in {1} about {2:.2f}%".format(sum2,sum, per2))

Number of expected loss are 355 times in 698 about 50.86%
Number of expected gain are 342 times in 698 about 49.00%

In [35]:
print(sum1)

print(sum2)

print(per1)
print(per2)

355
342
50.85959885386819
48.99713467048711